
platform :ios, '9.0'

target 'ObjCVoiceCallingApp' do
  use_frameworks!
  pod 'Crashlytics'

  target 'ObjCVoiceCallingAppTests' do
    inherit! :search_paths
  end

  target 'ObjCVoiceCallingAppUITests' do
    inherit! :search_paths
  end

end
