
platform :ios, '9.0'

target 'ObjCVoiceCallingApp' do
  use_frameworks!
  pod 'Google/SignIn'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Instabug'

  target 'ObjCVoiceCallingAppTests' do
    inherit! :search_paths
  end

  target 'ObjCVoiceCallingAppUITests' do
    inherit! :search_paths
  end

end
