# platform :ios, '9.0'

target 'SwiftVoiceCallingApp' do
	
  use_frameworks!
#  pod 'APAddressBook/Swift'
    pod 'APAddressBook'
    pod 'ReachabilitySwift'
  
  # Pods for SwiftVoiceCallingApp

  target 'SwiftVoiceCallingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftVoiceCallingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
