platform :ios, '10.0'

target 'SwiftVoiceCallingApp' do
	
  use_frameworks!
  pod 'APAddressBook/Swift'
  
  # Pods for SwiftVoiceCallingApp

  target 'SwiftVoiceCallingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftVoiceCallingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
