platform :ios, '12.0'

target 'SwiftVoiceCallingApp' do
	
  use_frameworks!
  pod 'APAddressBook/Swift'
  pod 'PlivoWebRTC', '1.1.5-beta'
  #pod 'PlivoVoiceKit', :path => '../../plivo-ios-sdk-webrtc'
  #pod 'PlivoVoiceKit', '2.2.3-beta'
  
  # Pods for SwiftVoiceCallingApp

  target 'SwiftVoiceCallingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftVoiceCallingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
